import { createApi } from '@reduxjs/toolkit/query/react';
import baseQueryWithReauth from '../apiSlice';

export const clientPaymentApiSlice = createApi({
  reducerPath: 'clientPaymentApiSlice',
  baseQuery: baseQueryWithReauth,
  tagTypes: ['Payment', 'CourseAccess', 'Purchases'],
  endpoints: (builder) => ({
    // Create payment link for course (can accept courseId string or { courseId, planId } object)
    createPaymentLink: builder.mutation({
      query: (payload) => {
        // Support both old format (string courseId) and new format (object with courseId and optional planId)
        const body = typeof payload === 'string' 
          ? { courseId: payload }
          : { courseId: payload.courseId, planId: payload.planId };
        
        return {
          url: '/common/payment/checkout',
          method: 'POST',
          body,
        };
      },
      invalidatesTags: ['Payment', 'Purchases'],
    }),

    // Check if user has access to a course
    checkCourseAccess: builder.query({
      query: (courseId) => `/common/payment/access/course/${courseId}`,
      providesTags: (result, error, courseId) => [
        { type: 'CourseAccess', id: courseId },
      ],
    }),

    // Get user's purchases
    getUserPurchases: builder.query({
      query: () => '/common/payment/purchases',
      providesTags: ['Purchases'],
    }),

    // Batch check access for multiple courses (efficient)
    batchCheckCourseAccess: builder.mutation({
      query: (courseIds) => ({
        url: '/common/payment/access/batch',
        method: 'POST',
        body: { courseIds },
      }),
      invalidatesTags: ['CourseAccess'],
    }),

    // Get available plans for a course
    getCoursePlans: builder.query({
      query: (courseId) => `/common/payment/course/${courseId}/plans`,
      providesTags: (result, error, courseId) => [
        { type: 'Payment', id: `course-plans-${courseId}` },
      ],
    }),

  }),
});

// RTK Query automatically generates all hooks including lazy hooks
export const {
  useCreatePaymentLinkMutation,
  useCheckCourseAccessQuery,
  useGetUserPurchasesQuery,
  useBatchCheckCourseAccessMutation,
  useLazyCheckCourseAccessQuery, // Auto-generated by RTK Query from checkCourseAccess
  useGetCoursePlansQuery,
  useLazyGetCoursePlansQuery, // Auto-generated lazy hook
} = clientPaymentApiSlice;

