# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - cryptoBuzz-backend

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: CryptoBuzz-be/package-lock.json

      - name: Install dependencies, build, and test
        working-directory: CryptoBuzz-be
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: Package application for deployment
        run: |
          cd CryptoBuzz-be
          zip -r ../release.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EDC84B0317C34C789BF0A4080F1842A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D74A9B2104CF4C768AA2E65BC88F0879 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B51BF8285D9944268F77DCC868A355C5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cryptoBuzz-backend'
          slot-name: 'Production'
          package: release.zip
