# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Vite app to Azure Web App - cryptoBuzz-educator (Staging)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build (Educator)
        working-directory: CryptBuzz-edu
        env:
          VITE_API_URL: ${{ secrets.STAGING_VITE_API_URL }}
          VITE_APP_API_URL: ${{ secrets.STAGING_VITE_APP_API_URL }}
          VITE_APP_NAME: ${{ secrets.STAGING_VITE_APP_NAME }}
          VITE_APP_VERSION: ${{ secrets.STAGING_VITE_APP_VERSION }}
          GENERATE_SOURCEMAP: ${{ secrets.STAGING_GENERATE_SOURCEMAP }}
          VITE_APP_CRM_API_KEY: ${{ secrets.STAGING_VITE_APP_CRM_API_KEY }}
          VITE_APP_STREAM_API_KEY: ${{ secrets.STAGING_VITE_APP_STREAM_API_KEY }}
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm install --force
          npm run build
          cd dist
          zip -r ../site.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0CF7B85673A541B98EC1AE44D892B17F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5BEEB2A5CA948E5B01EE3FAC4E76BF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50D1A4407B504963974AC99F6CA3659B }}

      - name: Deploy to Azure Web App (Educator)
        uses: azure/webapps-deploy@v3
        with:
          app-name: cryptoBuzz-educator
          slot-name: staging
          package: CryptBuzz-edu/site.zip
