# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - criptobuzz-admin

# on:
#   push:
#     branches:
#       - staging
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build --if-present
#           npm run test --if-present

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: .

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E459827F87204BE291C02F1F73B0EF97 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2A2967BF594E4121AF39A8ACCBE32181 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E6599DAA36242009D0F3AF89E57F065 }}

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'criptobuzz-admin'
#           slot-name: 'Production'
#           package: .
          



name: Build and deploy Node.js app to Azure Web App - criptobuzz-admin-fe

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: CryptoBuzz-admin
        run: npm install --force 
             npm install express

      - name: Build project with ENV
        working-directory: CryptoBuzz-admin
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_ENV: ${{ secrets.VITE_ENV }}
          VITE_SOCKET_URL: ${{ secrets.VITE_SOCKET_URL }}
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: CryptoBuzz-admin/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E459827F87204BE291C02F1F73B0EF97 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2A2967BF594E4121AF39A8ACCBE32181 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E6599DAA36242009D0F3AF89E57F065 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: criptobuzz-admin
          slot-name: Production
          package: .